### ISSUE TITLE
Class 'NorseBlue\ValueObjects\Immutable\ImmutableSimpleValueObject' not found 

### ISSUE THREAD

**Issue by peter279k** [norse-blue/php-string-extensions-inflections#1]
**Describe the bug**

This bug is related to [this](https://github.com/norse-blue/php-scalar-objects/issues/3).

**Environment**
The development environment is same as that issue.

**To Reproduce**
The reproduced steps are same as that issue.

**Expected behavior**
There's not error message.

**Screenshots**
There's no screenshot at this moment.

**Additional context**
The additional context is same as that issue.

This latest Travis CI build log is available [here](https://travis-ci.com/norse-blue/php-string-extensions-inflections/jobs/229075049).

**Comment by axelitus** [comment]
See related issue norse-blue/php-scalar-objects#3

**Comment by axelitus** [comment]
This issue is fixed in [Release 0.1.0](https://github.com/norse-blue/php-string-extensions-inflections/releases/tag/0.1.0).
